name: "Run Action with Different Inputs and Node.js Versions"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        user_name: ["Alice", "Bob", "Charlie"]
        node_version: ["14", "16", "18", "20"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Run the action with matrix input
        env:
          USER_NAME: ${{ matrix.user_name }}
        run: node src/index.js